apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
type: Opaque
data:
  db_url: bW9uZ29kYitzcnY6Ly9XZWJfUHJvamVjdDp5STJQZ1NBNWtON1NaQ1hKQHdlYi10ZXJtLXByb2plY3QuMHhxNHcubW9uZ29kYi5uZXQvQ29tbXVuZURyb3A/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9V2ViLVRlcm0tUHJvamVjdA==
  stripe_secret_key: c2tfdGVzdF81MVF2TEl0RjNhTkRvS3h3VTlxcU9raUpTMlVqbG5xUnJvWXM4ZllIRUdYU1U0RXBSODRQTXBNSDVLajRONVJrTTA0dWpyTnppOTJ1Yk5mYzR2cXlOWWVsaDAwZjVpdmRFM00K
